name: Robot Framework Test

on:
  workflow_dispatch: # Pode ajustar os gatilhos conforme necessário

jobs:
  test:
    runs-on: ubuntu-latest  # Pode ajustar o sistema operacional conforme necessário

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clona o repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8  # Escolha a versão correta do Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instale as dependências do seu projeto

    - name: Run Robot Framework tests
      run: |
        robot --outputdir ${{ github.workspace }}/logs ${{ github.workspace }}/test/features/  # Define o diretório de saída para os logs

    - name: Copy log files
      run: |
        mkdir -p ${{ github.workspace }}/logs_backup  # Cria um diretório para backup dos logs
        cp ${{ github.workspace }}/logs/*.log ${{ github.workspace }}/logs_backup/  # Copia os arquivos de log para o diretório de backup

    - name: Compress log files
      run: |
        cd ${{ github.workspace }}/logs_backup/
        zip -r logs_backup.zip .  # Compacta os arquivos de log em um arquivo zip

    - name: Upload log files
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${{ github.workspace }}/logs_backup/logs_backup.zip
