name: Robot Framework Test

on:
  workflow_dispatch: # Pode ajustar os gatilhos conforme necessário

jobs:
  test:
    runs-on: ubuntu-latest  # Pode ajustar o sistema operacional conforme necessário

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clona o repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Escolha a versão correta do Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instale as dependências do seu projeto

    - name: Run Robot Framework tests
      run: |
        robot ${{ github.workspace }}/test/features/*.robot  # Substitua pelo caminho correto para seus testes
